(deftheme dark-earth
  "Created 2017-11-01.")

(custom-theme-set-faces
 'dark-earth
 '(default ((t (:inherit default :stipple nil :background "#2c2826" :foreground "#bd987f" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 128 :width normal :foundry "PfEd" :family "Fantasque Sans Mono"))))
 '(cursor ((t (:background "#fecb52" :foreground "#fecb52"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:background "#F1F1F1" :foreground "#bd987f"))))
 '(escape-glyph ((t (:weight bold :foreground "#0E0E0E"))))
 '(minibuffer-prompt ((t (:height 1.0 :foreground "#0E0E0E"))))
 '(highlight ((t (:background "#F1F1F1"))))
 '(region ((t (:foreground "#F6F6F6" :background "#616161"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#F1F1F1"))))
 '(trailing-whitespace ((t (:background "#3C3C3C"))))
 '(font-lock-builtin-face ((t (:foreground "#ffdac2" :weight bold))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#9E9E9E"))))
 '(font-lock-comment-face ((t (:foreground "#616161"))))
 '(font-lock-constant-face ((t (:weight bold :foreground "#0E0E0E"))))
 '(font-lock-doc-face ((t (:weight bold :slant italic :foreground "#616161"))))
 '(font-lock-function-name-face ((t (:foreground "#ffdac2"))))
 '(font-lock-keyword-face ((t (:foreground "#b09045" :weight bold))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#0E0E0E"))))
 '(font-lock-preprocessor-face ((t (:foreground "#252525"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#616161"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#0E0E0E"))))
 '(font-lock-string-face ((t (:foreground "#fecb52" :slant normal))))
 '(font-lock-type-face ((t (:foreground "#ffdac2" :underline t))))
 '(font-lock-variable-name-face ((t (:foreground "#090909"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#252525"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#0E0E0E"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#252525"))))
 '(fringe ((t (:weight bold :foreground "#C3C3C3"))))
 '(header-line ((t (:inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:height 1.0 :box nil :inverse-video nil :foreground "black" :background "grey85"))))
 '(mode-line-buffer-id ((t (:weight bold :inherit (sml/filename)))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:height 1.0 :box nil :inverse-video nil :foreground "grey20" :background "#fdf6e3"))))
 '(isearch ((t (:weight bold :foreground "#252525" :background "#DADADA"))))
 '(isearch-fail ((t (:foreground "#0E0E0E" :background "#C3C3C3"))))
 '(lazy-highlight ((t (:weight bold :foreground "#252525" :background "#E8E8E8"))))
 '(match ((t (:weight bold :foreground "#252525" :background "#F6F6F6"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(js2-function-param ((t (:foreground "#98755d")))))

(provide-theme 'dark-earth)
