(progn
  (require 'setup-packages)
  (require 'setup-ivy)
  (require 'setup-ux)
  (require 'setup-editor)
  (require 'setup-evil)
  (require 'setup-projectile)
  (require 'setup-magit)
  (require 'setup-company)
  (require 'setup-python)
  (require 'setup-clojure)
  (require 'setup-js)
  (require 'setup-web))

(provide 'settings)
