(progn
  (require 'setup-packages)
  (require 'setup-ivy)
  (require 'setup-ux)
  (require 'setup-editor)
  (require 'setup-evil)
  (require 'setup-projectile)
  (require 'setup-magit)
  (require 'setup-company)
  ;; skonczyles tu
  (require 'setup-python)
  (require 'setup-clojure)
  (require 'setup-js)
  (require 'setup-web)
  ;; (require 'setup-cl)
  ;; (require 'setup-scheme)
  ;; (require 'setup-nlinum)
  (require 'setup-which-key))

(provide 'settings)
